name: deeplearning-coursera
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.7
- jupyterlab
- pip
- ipykernel
- pandas
- numpy
- h5py
- scipy
- pillow
- matplotlib
- pytorch
- torchvision
